application: wikifactorynet
version: 1
runtime: go
api_version: go1

handlers:
- url: /gfx
  static_dir: gfx
- url: /static
  static_dir: build
  expiration: "30d"
- url: /favicon.ico
  static_files: gfx/favicon.ico
  upload: gfx/favicon.ico
  expiration: "1d"
- url: /lib
  static_dir: lib
- url: /.*
  script: _go_app
